# Site settings
title: Raytek Solutions
email: contact@rayteksolutions.com
description: Professional mini split installation services starting at $750*. Expert HVAC solutions for your home or business in Phoenix, Arizona.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rayteksolutions.com" # the base hostname & protocol for your site

# Social media
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
